import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/layout/navbar";
import FooterSection from "@/components/layout/footer";
import { SearchProvider } from "@/components/home/context/search-context";
import { UserProvider } from "@/components/login/context/user-context";
import Providers from "@/providers/snackbar-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SearchProvider>
          <UserProvider>
            <Providers>
              <Navbar />
              {children}
              <FooterSection />
            </Providers>
          </UserProvider>
        </SearchProvider>
      </body>
    </html>
  );
}
